services:
  - type: web
    name: martins-density-map
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        value: Martins Admin
      - key: DATABASE_URL
        fromDatabase:
          name: martins-density-db
          property: connectionString

databases:
  - name: martins-density-db
    plan: basic-256mb

GOOGLE_MAPS_API_KEY=AIzaSyD-niMQ5MWxPbSG-kehIIHzlgv89Y0TbaQ

