UPLOAD_COLUMNS = [
    "MF File",
    "Deceased Name",
    "Deceased Surname",
    "DOD",
    "Address",
    "City",
    "Province",
    "Country",
    "Next of Kin Name",
    "Next of Kin Surname",
    "Relationship",
    "Contact Number",
    "Church Name",
    "Pastor Name",
    "Church Address",
    "Church City",
    "Church Province",
    "Church Country",
]

EXPORT_COLUMNS = [
    "MF File",
    "Deceased Name",
    "Deceased Surname",
    "DOD",
    "Address",
    "City",
    "Province",
    "Country",
    "Full Address",
    "Latitude",
    "Longitude",
    "Weight",
    "Next of Kin Name",
    "Next of Kin Surname",
    "Relationship",
    "Contact Number",
    "Church Name",
    "Pastor Name",
    "Church Address",
    "Church City",
    "Church Province",
    "Church Country",
]

PROVINCES = [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
    "Western Cape",
]
